# Generated by Django 2.0.1 on 2019-06-26 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='Atracoes'),
        ),
    ]
