# Generated by Django 2.0.1 on 2019-06-28 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0002_avaliacao_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacao',
            name='foto',
        ),
    ]
