# Generated by Django 2.0.1 on 2019-06-19 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atracao',
            name='aprovado',
        ),
    ]
