# Generated by Django 2.0.1 on 2019-06-26 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0002_remove_atracao_aprovado'),
    ]

    operations = [
        migrations.AddField(
            model_name='atracao',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='Atracoes'),
        ),
    ]
